### ISSUE TITLE
How does docker.for.win.localhost or docker.for.mac.host.internal work

### ISSUE THREAD

**Issue by VenkateshSrini** [kata-containers/community#105]
Hi,
I have a container (docker), where the container access a database on the same VM that hos the container. Since they are all on windows, we use the docker.for.win.localhost to access the database. In general, in Kata if the same things needs to work then will this method work ?

When I say docker.for.win.localHost will it resolve to the Host machine or the light weight VM that host the container ?

**Comment by grahamwhaley** [comment]
Hi @VenkateshSrini - first question - are these Windows based containers? If so, Kata does not currently support those, only Linux based containers on Linux hosts.

**Comment by VenkateshSrini** [comment]
No they are Linux container communicating to DB on windows box

**Comment by grahamwhaley** [comment]
I'm still not quite clear on where the Windows is - is the VM Windows that is running Docker - have you tried/managed to run Kata in docker-for-windows?
Anyway, re-reading your question, afaik the name should resolve to the host, not the lightweight VM - if it does resolve to the lightweight VM then I suspect we'd have a bug, and we'd fix it ;-)

/cc @amshinde @mcastelino

**Comment by VenkateshSrini** [comment]
I'm asking this question purely from Docker perspective, where I run docker on windows. I have Linux VM on my hyper V in which my container runs. The Postgres server is still in Windows bare server. If I move to Kata then I want to know what will happen. Basically it is a preparatory cycle for using Kata. 

Kata will not run on windows, I see that from the documentation

**Comment by grahamwhaley** [comment]
Ah, maybe I see now - please correct if this is wrong - currently you have (thanks http://asciiflow.com/ for making this easy to draw...):

```
+-------------------------------------------------------+
|                                    Windows(host)      |
|                                                       |
|    +---------+    +--------------------------------+  |
|    |         |    |       HyperV(Linux)            |  |
|    | DB      |    |                                |  |
|    |         |    |                                |  |
|    +---^-----+    |     +------------------+       |  |
|        |          |     |  Container       |       |  |
|        +----------------+                  |       |  |
|                   |     |                  |       |  |
|                   |     |                  |       |  |
|                   |     |                  |       |  |
|                   |     +------------------+       |  |
|    +----------+   |                                |  |
|    |          |   |                                |  |
|    | Docker   |   |    +-------------------+       |  |
|    |  cmdline +------->+  dockerd          |       |  |
|    |          |   |    +-------------------+       |  |
|    |          |   |                                |  |
|    +----------+   +--------------------------------+  |
|                                                       |
|                                                       |
+-------------------------------------------------------+
```

and you want to know if that will still work if you move to Kata, like:
```
+-------------------------------------------------------+
|                                    Windows(host)      |
|                                                       |
|    +---------+    +--------------------------------+  |
|    |         |    |       HyperV(Linux)            |  |
|    | DB      |    |   +-----------------------+    |  |
|    |         |    |   |   Kata VM             |    |  |
|    +---^-----+    |   | +------------------+  |    |  |
|        |          |   | |  Container       |  |    |  |
|        +----------------+                  |  |    |  |
|                   |   | |                  |  |    |  |
|                   |   | |                  |  |    |  |
|                   |   | |                  |  |    |  |
|                   |   | +------------------+  |    |  |
|    +----------+   |   |                       |    |  |
|    |          |   |   +-----------------------+    |  |
|    | Docker   |   |    +-------------------+       |  |
|    |  cmdline +------->+  dockerd          |       |  |
|    |          |   |    +-------------------+       |  |
|    |          |   |                                |  |
|    +----------+   +--------------------------------+  |
|                                                       |
|                                                       |
+-------------------------------------------------------+
```

and in particular, if the name resolution is going to work?

**Comment by VenkateshSrini** [comment]
Perfect. Tremendous effort to understand. I truely appreciate it

**Comment by mcastelino** [comment]
@VenkateshSrini the name resolution will work under if the nameserver is reachable from the container (i.e. not handled by dockerd via the 127.0.0.11:... ). 

Can you tell us what your container resolv.conf looks like within the container running in Hyper-V linux

**Comment by VenkateshSrini** [comment]
IN docker for windows where can I see this ?

**Comment by mcastelino** [comment]
@VenkateshSrini inside a container run `cat /etc/resolv.conf`

**Comment by VenkateshSrini** [comment]
Hi, I  have asked our operator on these. Meanwhile can you please tell me what the value should be so that the resolution happens to Windows Host? This is more a checklist that we are preparing when we want to migrate from current docker runtime to Kata

**Comment by amshinde** [comment]
@VenkateshSrini The DNS should not be pointing to 127.0.0.11, which is done so by docker in certain cases.
If you run a `cat /etc/resolv.conf` inside your container, we will be able to give you an answer.
