### ISSUE TITLE
Should we update our slogan?

### ISSUE THREAD

**Issue by gnawux** [kata-containers/community#124]
Our cover sentence

> The speed of containers, the security of VMs

has been there for two years, and I am thinking about renew it recently.

My candidate is

> Virtualization for CloudNative

reasons:

1. Kata is about not only **security** but also for general isolation in many cases.
2. **Virtualization** is a more technical (neutral) word
3. It's shorter and exactly match the description "*building lightweight virtual machines that seamlessly plug into the containers ecosystem.*" 

Inputs are welcome. @kata-containers/architecture-committee

**Comment by raravena80** [comment]
I think, we probably want to add something about how Kata is useful for certain types of workloads and use cases. i.e Serverless, and Edge computing cases.
