### ISSUE TITLE
Information needed to attend Architecture Committee meeting missing 

### ISSUE THREAD

**Issue by CraigSterrett** [kata-containers/community#145]
The community page lacks details for attendance of the Architecture Committee meeting. The information is available on the community page https://katacontainers.io/community/. 
Need to add link to etherpad and possibly also link back to https://katacontainers.io/community/ for more information

**Comment by mvincerx** [comment]
Let's add a link to the .io site for ease of reference: https://katacontainers.io/community/

**Comment by mvincerx** [comment]
Feel free to assign this issue to me.

**Comment by grahamwhaley** [comment]
done

**Comment by mvincerx** [comment]
Thanks
