### ISSUE TITLE
Streamline user-nav based on roles, CONTRIBUTING guide. 

### ISSUE THREAD

**Issue by mvincerx** [kata-containers/community#150]
**Which feature do you think can be improved?**

Streamline [CONTRIBUTORS guide](https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md) to simplify user navigation, improve user experience/orientation, and replace GitHub conventions with external links where possible. 

**How can it be improved?**
- [ ]  Improve user nav: Clearly address "ways to contribute" based on user roles. TCS and @jodh-intel  identified 7 primary user roles.   Refer also to top-level [Wiki Getting Started ](https://github.com/kata-containers/community/wiki/Getting-Started-Contributor-Guide). The intent is to ease the means by which contributors find the resources they need and get started. 

**Additional Information**

Regarding how to contribute, users are given two distinctly different "landing pages": 
- https://github.com/kata-containers/community/wiki/Getting-Started-Contributor-Guide
- https://github.com/kata-containers/community#contributors

This is confusing. This **macro issue** is now part of a larger effort to reorganize documentation, found in this [GitHub Project](https://github.com/kata-containers/documentation/projects/1) 

Other options: 

- Use 1 top-level Github Pages that includes multiple READMEs and CONTRIBUTING hyperlink. 

- Use  only one top-level pinned repo, like [Clear Linux OS](https://github.com/clearlinux). In this case, *one README.md* at [kata-containers](https://github.com/kata-containers/kata-container) can reference all other repos' READMEs.

- In [kata-containers/kata-containers](https://github.com/kata-containers/kata-containers) , reference Getting Started immediately. 

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?

Yes.

**Comment by jodh-intel** [comment]
@mvincerx - any update on this?

**Comment by mvincerx** [comment]
This was addressed in https://github.com/kata-containers/community/pull/153/files#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055R54

See `CONTRIBUTING.md`, **Contributor roles** header
https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#contributor-roles

**Comment by jodh-intel** [comment]
Ok, thanks @mvincerx - closing.

**Comment by mvincerx** [comment]
Thanks, @jodh-intel
