### ISSUE TITLE
Improve UI components in CONTRIBUTING guide

### ISSUE THREAD

**Issue by mvincerx** [kata-containers/community#152]
**Which feature do you think can be improved?**

- [ ] Clean up sections, like each “Note”, which displays incorrectly with grey bar.

- [ ] Improve description for “Patch Format” and consider using new graphic/diagram.
       An  annotated graphic  may help pinpoint written requirements, given that requirements are 
       somewhat onerous.  Consider reducing the requirements for PRs in Documentation 
       Add all requirements in a bulleted list (Include the 75 char limit of commit msg.). 

**Additional Information**

See parent Issue GH-150

**Before raising this feature request**

Yes

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?

**Comment by c3d** [comment]
@mvincerx @DougTW Assigning to you and removing need-review label
