### ISSUE TITLE
Can we add a TODO/Ongoing document for Kata on arm in community repo?

### ISSUE THREAD

**Issue by justin-he** [kata-containers/community#154]
**Is your feature request related to a problem? Please describe.**
There are some special topics/features on arm which are different with other arches. E.g. multiarch,
vcpu hotplug, nested virtualization, obs ...
It would be better we can add a document to track the process of those items.

**Describe the solution you'd like**

Add a doc in community repo

**Describe alternatives you've considered**

Any suggestions?

**Additional context**

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?
Yes

**Comment by justin-he** [comment]
@kata-containers/architecture-committee @kalyxin02 @Pennyzct

**Comment by Pennyzct** [comment]
agreed. ;) cc @egernst for also bringing up the tracking issue on arm.

**Comment by gnawux** [comment]
I am fine to see what the PR would like. And I wonder why isn't it located in the documentation repo.

**Comment by jodh-intel** [comment]
Yes, sounds good @justin-he. In fact, if you need task tracking, you could always create a GitHub project board for this? Something like:

- https://github.com/kata-containers/kata-containers/projects/1
