### ISSUE TITLE
Document the decision of no new features for 1.x branches.

### ISSUE THREAD

**Issue by fidencio** [kata-containers/community#157]
In several PRs @bergwolf [commented](https://github.com/kata-containers/runtime/pull/2703#issuecomment-635885801) that no new features should be merged in the 1.x branches and that the contributor should open the PR against https://github.com/kata-containers/kata-containers.

While the comment makes sense, would be really good to have a PR opened, approved, and merged somewhere about this decision. It'd would help not only to avoid the confusion from the contributors, but also help the maintainers to have everything documented and recorded so we could just post a link about the decision taken.

What do the community think? Does this idea make sense?

**Comment by bergwolf** [comment]
We have discussed this in PTG and the conclusion is to allow new features to be in 1.x releases but they must be ported to 2.0-dev branch as well. More details are recored at 
https://etherpad.opendev.org/p/victoria-ptg-kata

**Comment by ariel-adam** [comment]
@fidencio do we still need this one?
