### ISSUE TITLE
There's no information about the elections' results for the 2020-09 round

### ISSUE THREAD

**Issue by fidencio** [kata-containers/community#206]
Subject says it all. :-)

**Comment by ariel-adam** [comment]
Do we need to add content to: https://github.com/kata-containers/community/blob/master/elections/arch-committee-2020-09/Results.md ?

**Comment by ariel-adam** [comment]
@lifupan what do you think?

**Comment by lifupan** [comment]
> @lifupan what do you think?

Yeah, you are right, we had missed to publish the results, I have send a PR to publish it: https://github.com/kata-containers/community/pull/209
