### ISSUE TITLE
docs: Update the wiki

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/community#215]
It seems that this document needs to be updated 
https://github.com/kata-containers/community/wiki/Controlling-the-CI
maybe we should remove the content that belongs to kata 1.x (like travis, zuul, etc), and update only for kata 2.x, wdyt @fidencio @chavafg ?

**Comment by fidencio** [comment]
Yes, please! :-)

**Comment by GabyCT** [comment]
@fidencio @chavafg maybe we should move that document into the tests repository mainly because that is the first place where people are looking for documentation about tests and CI, it seems at least for me that this repository has not enough visibility and I believe that even if I do some changes here ..the confusion about the CI jobs will still continue but wdyt

**Comment by fidencio** [comment]
@GabyCT, I agree that the tests repo has a better visibility.  Please, go ahead with the change and tag me for a review there.
Thanks!

**Comment by GabyCT** [comment]
Closing this issue as it has been solved
