### ISSUE TITLE
Broken Slack invitation link

### ISSUE THREAD

**Issue by mlejva** [kata-containers/community#223]
I tried to join the official Slack workspace but the invitation link in the [Join Us](https://github.com/kata-containers/kata-containers/blob/main/docs/install/gce-installation-guide.md) section is broken.

**Comment by ariel-adam** [comment]
@kata-containers/community Any idea?

**Comment by Jakob-Naucke** [comment]
[This](https://github.com/kata-containers/community#join-us) (among other places, maybe?) is where the broken link is.

**Comment by uran0sH** [comment]
Slack invitation link is no longer active

**Comment by sadmankiba** [comment]
The slack invitation link is broken again. [Here](https://github.com/kata-containers/community/blob/2fe7125de683f0f05d32f145f2df0bf0d723d84f/README.md?plain=1#L44).
