### ISSUE TITLE
releases: Shall we reevaluate the release candence for the 2.4.0 and onwards?

### ISSUE THREAD

**Issue by fidencio** [kata-containers/community#243]
During a few release cycles we experimented with a shorter cadence for our releases, which combined with the maintainence of only one stable branch, has had some impact on our users.

The current way of handling releases, as described [here](https://github.com/kata-containers/kata-containers/blob/main/docs/Stable-Branch-Strategy.md) has made a release life-cycle reasonably short, maybe way too short for some companies taste.

Moving to a longer period could have a negative impact of waiting for too long in order to get something out, and also increasing the maintainence burden on the stable branch, but then companies could be able to rely more on the stable branches.

This, [combined with a LTS proposal made some time ago](https://github.com/kata-containers/kata-containers/issues/2657) could be explored for finding the right balance between what we currently have and what we may want to do.

/cc @amshinde @bergwolf @egernst @sameo @kata-containers/redhat

**Comment by jodh-intel** [comment]
+1 to re-evaluating. Sounds like a good topic for the AC meeting. But also, we should explore the question in the user survey to get as much exposure around the question as possible.

**Comment by fidencio** [comment]
The form was sent out: https://forms.gle/nWM7kdcfX88Edkkt7 and http://lists.katacontainers.io/pipermail/kata-dev/2021-December/002296.html

**Comment by fidencio** [comment]
During the architecture committee meeting held on Dec 14th, 2021, we agreed on following the suggestion of having minor releases every 4 months, with patch releases happening every month.  The stable branch will be maintained for 4 months, and the wiki is already updated (see: https://github.com/kata-containers/community/wiki/Release-Team-Rota).

I'll raise a new issue to update https://github.com/kata-containers/kata-containers/blob/main/docs/Stable-Branch-Strategy.md and I'm closing this one now.

**Comment by jodh-intel** [comment]
Thanks @fidencio ! Yep, a new table in that doc would summarise that nicely.
