### ISSUE TITLE
review-rota: Update members according to their disponibility

### ISSUE THREAD

**Issue by fidencio** [kata-containers/community#244]
Folks, the Review Rota is how we try to balance the review work between the team, and there we have folks who volunteered themselves to help with reviews.  However, we've always been "appending" names to the list, and sometimes not properly advertising the Rota.

In order to help the project to organise itself better, I'd like to ask everyone who has its name there their intention to be kept or removed from there, and also open this to the community and ask who would like to be added to the Review Rota.

It's good to remember that although this is something to be done on "best effort", if you usually don't have the capacity to jump on those, would be better to have your name removed from the list so we have a better understanding of the team's capacity to review the amount of work contributed to the project, and also how we can distribute better the folks who have the capacity to do so.

Last but not least, please, removing your name from the list is **not** a bad thing, at all.  Priorities change all the time, we become busier than expect for several months, and then we may have free time again (and be re-added to the list without any issue).

Here's the list of names that are currently part of the review-rota:
@jongwu @c3d @snir911 @GabyCT @dborquez @bergwolf @Jakob-Naucke @amshinde @cmaf @liubin @fidencio @gkurz @egernst @chavafg @fupan @marcel-apf @jcvenegas @tedyu @Bevisy @jodh-intel @pmores @raravena80 @devimc 

Please, let me know in case you have interest to either be removed or kept in the list.

**Comment by gkurz** [comment]
@fidencio , please keep my name in the list.

**Comment by Jakob-Naucke** [comment]
@fidencio I would like to be kept.

**Comment by marcel-apf** [comment]
Hi Fabiano,

On Mon, Nov 22, 2021, 14:56 Fabiano Fidêncio ***@***.***>
wrote:

> Folks, the Review Rota is the how we try to balance the review work
> between the team, and there we have folks who volunteered themselves to
> help with reviews. However, we've always been "appending" names to the
> list, and sometimes not properly advertising the Rota.
>
> In order to help the project to organise itself better, I'd like to ask
> everyone who has its name there their intention to be kept or removed from
> there, and also open this to the community and ask who would like to be
> added to the Review Rota.
>
> It's good to remember that although this is something to be done on "best
> effort", if you usually don't have the capacity to jump on those, would be
> better to have your name removed from the list so we have a better
> understanding of the team's capacity to review the amount of work
> contributed to the project, and also how we can distribute better the folks
> who have the capacity to do so.
>
> Last but not least, please, removing your name from the list is *not* a
> bad thing, at all. Priorities change all the time, we become busier than
> expect for several months, and then we may have free time again (and be
> re-added to the list without any issue).
>
> Here's the list of names that are currently part of the review-rota:
> @jongwu <https://github.com/jongwu> @c3d <https://github.com/c3d> @snir911
> <https://github.com/snir911> @GabyCT <https://github.com/GabyCT> @dborquez
> <https://github.com/dborquez> @bergwolf <https://github.com/bergwolf>
> @Jakob-Naucke <https://github.com/Jakob-Naucke> @amshinde
> <https://github.com/amshinde> @cmaf <https://github.com/cmaf> @liubin
> <https://github.com/liubin> @fidencio <https://github.com/fidencio> @gkurz
> <https://github.com/gkurz> @egernst <https://github.com/egernst> @chavafg
> <https://github.com/chavafg> @fupan <https://github.com/fupan> @marcel-apf
> <https://github.com/marcel-apf> @jcvenegas <https://github.com/jcvenegas>
> @tedyu <https://github.com/tedyu> @Bevisy <https://github.com/Bevisy>
> @jodh-intel <https://github.com/jodh-intel> @pmores
> <https://github.com/pmores> @raravena80 <https://github.com/raravena80>
> @devimc <https://github.com/devimc>
>
> Please, let me know in case you have interest to either be removed or kept
> in the list.
>

As my responsibilities have shifted, I will not have enough time to really
help, please remove me from the list, at least for now.

Thank you,
Marcel

**Comment by snir911** [comment]
keep me in please

**Comment by cmaf** [comment]
@fidencio please keep my name

**Comment by jodh-intel** [comment]
ditto for me ;)

**Comment by jodh-intel** [comment]
If anyone else is reading this and would like to get involved in the rota, please do comment too as the more the better really. Also, most of us don't bite :tooth: :tooth: :smile:

**Comment by pmores** [comment]
Please remove me.

Thanks!

	pvl

**Comment by liubin** [comment]
Keep me in, please

**Comment by jongwu** [comment]
Please keep me in @fidencio , thanks.

**Comment by fidencio** [comment]
Folks, a second ping on everyone who didn't reply.

Again, please, remember that removing your name from the list is not a bad thing, at all. Priorities change all the time, we become busier than expect for several months, and then we may have free time again (and be re-added to the list without any issue), but we have to understand our current capacity.

@c3d @GabyCT @dborquez @bergwolf @amshinde @egernst @chavafg @fupan @jcvenegas @tedyu @raravena80 @devimc

**Comment by chavafg** [comment]
please remove me, thanks.

**Comment by dborquez** [comment]
@fidencio keep me in please

**Comment by devimc** [comment]
please remove me,  I'd like to continue reviewing but when I have cycles to do it

**Comment by egernst** [comment]
Kata4eva

please keep my name. Thanks @fidencio

**Comment by cmaf** [comment]
@fidencio I replied earlier to keep my name, but I won't be able to until next year so remove me in the meantime. Thanks!

**Comment by GabyCT** [comment]
please remove me, I will continue doing reviews but when I have cycles

**Comment by raravena80** [comment]
You can remove me for now. I'll re-join if and when I have more spare cycles. Thx.

**Comment by bergwolf** [comment]
Please keep me there, thanks @fidencio!

**Comment by lifupan** [comment]
@fidencio   please keep my name

**Comment by c3d** [comment]
@fidencio Please keep my name.

In addition, I'd like to take the opportunity to (re) advertise our weekly "backlog scrubbing" meeting on Tuesdays 😄 

I was unlucky enough to be put at least once on "active duty" while on PTO. I'll try to pay more attention to the calendar this time.

**Comment by amshinde** [comment]
@fidencio Please keep my name.

**Comment by fidencio** [comment]
So, based on the answers we have till now, the Review Rota looks like:

| YYYY-MM-DD |      APAC           |              EMEA            |          AMER                  | Notes
| ---------- | --------------------| ---------------------------- | ------------------------------ |--------
2021-12-06 | jongwu | c3d snir911 | dborquez |  
2021-12-13 | bergwolf | Jakob-Naucke | amshinde |  
2021-12-20 | liubin | fidencio gkurz | egernst |  
2021-12-27 | fupan |   | jcvenegas tedyu |  
2022-01-03 | Bevisy | jodh-intel |   |  
2022-01-10 | jongwu | c3d snir911 | dborquez |  
2022-01-17 | bergwolf | Jakob-Naucke | amshinde  |  
2022-01-24 | liubin | fidencio gkurz | egernst |  
2022-01-31 | fupan |   | jcvenegas tedyu |


What I'd like to suggest is:
| YYYY-MM-DD |      APAC           |              EMEA            |          AMER                  | Notes
| ---------- | --------------------| ---------------------------- | ------------------------------ |--------
2021-12-06 | jongwu | snir911 | dborquez |  
2021-12-13 | bergwolf amshinde | Jakob-Naucke |  |  
2021-12-20 | liubin | fidencio gkurz | egernst |  
2021-12-27 |   |   |   |  
2021-01-03 | fupan |  c3d  | jcvenegas  |  
2022-01-10 | Bevisy | jodh-intel | tedyu  |  
2022-01-17 | jongwu | snir911 | dborquez |  
2022-01-24 | bergwolf amshinde | Jakob-Naucke |   |  
2022-01-31 | liubin | fidencio gkurz | egernst |  
2022-02-07 | fupan | c3d | jcvenegas |

Just to make it clear, the changes I'm proposing are:
1. Move @amshinde's from AMER to APAC, at least for now
2. Move @c3d (or could be @snir911, @gkurz, or myself) to a week where we don't have coverage in EMEA. (Christophe, let me know if you don't feel comfo rtable being moved to a week where you'd be working "alone" from next year, and we can figure out a better approach)
3. Move @tedyu to a week where there's no AMER coverage (but @jcvenegas could be one moved)
4. Removed the week between Christmas and New Year's from the rota as a whole bunch of folks will be off anyways.

Please, let me know if this suits you well and, if not, what suggestions you'd like to make.

Also, mind that we still don't know whether both Ted Yu or Carlos will have cycles to spend on this.

@jodh-intel, WDYT?

**Comment by c3d** [comment]
@fidencio Is the date supposed to be 2022?

**Comment by fidencio** [comment]
> @fidencio Is the date supposed to be 2022?

It's, at least till we get our DeLorean fixed. :-).  I fixed it in the table, thanks!

**Comment by jcvenegas** [comment]
@fidencio  this looks goot to me thanks for rebalance the calendar.

**Comment by fidencio** [comment]
Thanks everyone for the replies, I'm closing this one and you can see the updated table at: https://github.com/kata-containers/community/wiki/Review-Team-Rota#the-rota

Anyone who didn't reply (Ted Yu) got removed and can be re-added later if they wish to do so.

**Comment by dborquez** [comment]
@fidencio looks good to me, just to mention I will be on vacations on the first round 2021-12-06 but I will be ready for the second round 2022-01-17
