### ISSUE TITLE
Update AC meeting agenda link in README.md

### ISSUE THREAD

**Issue by zmlcc** [kata-containers/community#251]
The agenda link https://etherpad.opendev.org/p/Kata_Containers_2021_Architecture_Committee_Mtgs is obsolete. It should be changed to https://etherpad.opendev.org/p/Kata_Containers_2022_Architecture_Committee_Mtgs

**Comment by fidencio** [comment]
This was fixed as part of the https://github.com/kata-containers/www.katacontainers.io/pull/176

**Comment by fidencio** [comment]
Ops, sorry, no, this was not fixed yet. :-)
