### ISSUE TITLE
vPTG | April 4th ti 8th, 2022

### ISSUE THREAD

**Issue by fidencio** [kata-containers/community#257]
As discussed in the architecture committee meetings of March 8th, we should decide whether we will join the vPTG or not.

[1] Team Survey: https://openinfrafoundation.formstack.com/forms/april2022_vptg_survey
[2] Ethercalc Signup: https://ethercalc.openstack.org/7yxdas7suqnd
[3] PTG Registration: https://openinfra-ptg.eventbrite.com/

Please, as comments, add topics of what you'd like to see and based on that we can take a decision.

The deadline for signing up for that is March 11th.

**Comment by bergwolf** [comment]
I haven't followed closely the confidential container progress. If possible, I hope to see an update on the CC area, the current architecture, where we are, and what's the plan for 2022 etc.

The runtime-rs part can also share a similar update as I know many folks are not following up closely enough but do care a lot about its progress.

Another thing that I have in mind is the summary of the 2.4 release.  We had quite a few exciting features in the 2.4 release and it's good to highlight them in a public place/event. It can be followed by a planning discussion for 2.5.0 that is unfinished (IMO) in yesterday's AC meeting.

Just my 2 cents... If we are going to sign up the vPTG of cause!

**Comment by fidencio** [comment]
@bergwolf, we didn't get any response about this, but I think we can use future architecture committee meetings for those, and ask Sunny to do some advertisement on twitter.

WDYT?

**Comment by fidencio** [comment]
Cosing this one as we won't be having a slot on the next vPTG.
