### ISSUE TITLE
David Gibson moving on

### ISSUE THREAD

**Issue by dgibson** [kata-containers/community#270]
Hi folks,

I'm in the process of moving on from working on Kata to other projects.  I'll continue to wrap up the stuff I have underway, but I won't be taking on anything new.

Accordingly, can I please be removed from the maintainers list, @documentation group and anything else that means I get automatically CCed on lots of things.  I'd like to stay on the contributors list for now, to facilitate the things I'm wrapping up, assuming that's not complicated.

**Comment by fidencio** [comment]
@dgibson, I've removed you from all the groups apart from the `kata-containers` one, meaning you're still on the contributors list, at least till you change your mind.

On behalf of the Kata Containers community I'd like to thank you for all the patches provided and wish you the best on your new journey.

Have fun, that's the most important part, don't forget to have fun! :-)

**Comment by jodh-intel** [comment]
Hi @dgibson - +1 to @fidencio's comments. We really appreciate all the great work you have done for Kata!
