### ISSUE TITLE
Add @Megan-Wright to the `kata-containers` team

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/community#271]
@Megan-Wright (along with @GeorginaKin) has been helping with some of the confidential-containers work, on the weekly merges of the `main` branch into `CCv0` and with some of the CC CI testing, so it would be good to get her access to run tests and add labels to issues and PRs to help with this. Her PRs include:
- https://github.com/kata-containers/tests/pull/4590
- https://github.com/kata-containers/tests/pull/4612
- https://github.com/kata-containers/tests/pull/4695
- https://github.com/kata-containers/kata-containers/pull/4201
- https://github.com/kata-containers/kata-containers/pull/4116
- https://github.com/kata-containers/ci/pull/472

**Comment by wainersm** [comment]
I second that request. I worked with Megan and Georgina on most of the PRs included on this issue. They have been fundamental to expand the test coverage on Kata for Confidential Containers and the CCv0 branch merging work, we can trust on Megan and Georgina to run the tests and add labels to issues.

**Comment by fidencio** [comment]
+1.

**Comment by GabyCT** [comment]
+1

**Comment by bergwolf** [comment]
+1

**Comment by sameo** [comment]
+1

**Comment by fidencio** [comment]
I've sent the invitation for @Megan-Wright.  Megan, please, close this issue after you accept the invitation.

**Comment by Megan-Wright** [comment]
Thanks so much!
