### ISSUE TITLE
Add @GeorginaKin to the `kata-containers` team

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/community#272]
@GeorginaKin (along with @Megan-Wright) has been helping with some of the confidential-containers work, on the weekly merges of the `main` branch into `CCv0` and with some of the CC CI testing, so it would be good to get her access to run tests and add labels to issues and PRs to help with this. Her PRs include:
- https://github.com/kata-containers/tests/pull/4729
- https://github.com/kata-containers/tests/pull/4761
- https://github.com/kata-containers/tests/pull/4683
- https://github.com/kata-containers/kata-containers/pull/4221
- https://github.com/kata-containers/kata-containers/pull/4158

**Comment by wainersm** [comment]
I second that request. My https://github.com/kata-containers/community/issues/271#issuecomment-1129127022 applies here too.

**Comment by fidencio** [comment]
+1.

**Comment by GabyCT** [comment]
+1

**Comment by bergwolf** [comment]
+1

**Comment by sameo** [comment]
+1

**Comment by jodh-intel** [comment]
+1

**Comment by fidencio** [comment]
I've sent the invitation for @GeorginaKin.  Georgina, please, close this issue after you accept the invitation.

**Comment by stevenhorsman** [comment]
@fidencio - I seems like I misunderstood the permissions and groups and Megan & George being in `kata-containers` doesn't give them permission to update issues in the `tests` repos, which they also work on for their CC changes. I think I should have also requested access to the `tests` group for them, so is the best way to do that for me to create new issues asking for that approval?

**Comment by fidencio** [comment]
Done for both Georgina and Megan.
