### ISSUE TITLE
fgiudici - stepping down to community member

### ISSUE THREAD

**Issue by fgiudici** [kata-containers/community#273]
Hi  team!
   I will soon start to work on a new project. While I will keep following Kata Containers, I will not have much time to dedicate actively to the project. For this reason, I would like to ask to be removed from the Kata Containers organization teams I'm in:
- ci
- community
- cri-o
- external-contributors
- jenkins-admin
- kata-containers
- redhat
- tests

I am also one of the owners of the Kata Containers CRI-O upstream CI job: please, remove me from there too.
Many thanks for welcoming me in in this wonderful project, for all the talks, the reviews and the support! I really enjoyed it and I have had quite some fun  ❤️ 😃

**Comment by GabyCT** [comment]
Good luck and thanks for your work :)

**Comment by fidencio** [comment]
@fgiudici, have fun in your new journey and we'll cross paths! :-)
Thanks a lot for all the work we've done together, inside Red Hat, as part of the community, etc.  You'll be missed, so don't be a stranger! <3

**Comment by fidencio** [comment]
@fgiudici, you've been removed fro the teams!
