### ISSUE TITLE
Adding Anastassios Nanos as a maintainer

### ISSUE THREAD

**Issue by fidencio** [kata-containers/community#274]
@ananos has been actively contributing to Kata Containers for an year or so (if not more), is the maintainer of the Firecracker CI, has been helping the community with issues related to that, together with materials that people can use to get up to speed with Kata Containers and Firecracker.

Moreover, @ananos has been using Kata Containers on their side, providing some quite interesting talks about the project, and is just natural to have him as a maintainer.

/cc @amshinde, @bergwolf, @egernst, @sameo

**Comment by amshinde** [comment]
:+1:

**Comment by bergwolf** [comment]
+1

**Comment by sameo** [comment]
+1

**Comment by fidencio** [comment]
@ananos has been added to the kata-containers-maintainer group!
Thank you for all the contributions so far, and looking forward to work even more with you and all the folks from Nubificus!
