### ISSUE TITLE
Add @littlejawa to the kata-commiter team

### ISSUE THREAD

**Issue by wainersm** [kata-containers/community#289]
Julien ROPÉ (@littlejawa) is responsible for the integration of [CRI-O](https://github.com/cri-o/cri-o) and Kata Containers at Red Hat. He owns the CR-IO CI jobs on our Jenkins to ensure that changes on CRI-O won't break with Kata Containers (and vice-versa). He has helped with pull requests reviews on CI, releases and random areas since last year. Having Julien in the maintainers team will help to speed up fixes on CI and with the releases work.

Ref.: https://github.com/kata-containers/kata-containers/commits?author=littlejawa
Ref.: https://github.com/kata-containers/tests/commits?author=littlejawa

Cc @kata-containers/architecture-committee 
Cc @kata-containers/redhat

**Comment by fidencio** [comment]
+1 from my side, as we've been sharing the CRI-O CI responsibilities.

**Comment by gkurz** [comment]
Julien reviewed some PRs of mine for recent releases. I would have loved his approval to be accounted to speed things up.
So yes, I recommend Julien should be a [maintainer](https://github.com/orgs/kata-containers/teams/kata-containers-maintainer/members) or at least a [committer](https://github.com/orgs/kata-containers/teams/kata-containers-committer) like me.

**Comment by wainersm** [comment]
> Julien reviewed some PRs of mine for recent releases. I would have loved his approval to be accounted to speed things up. So yes, I recommend Julien should be a [maintainer](https://github.com/orgs/kata-containers/teams/kata-containers-maintainer/members) or at least a [committer](https://github.com/orgs/kata-containers/teams/kata-containers-committer) like me.

I didn't know we had the committer team as well. In this case, I change my proposal to include Julien on that group instead of maintainers.

**Comment by bergwolf** [comment]
+1, and thanks for taking care of the CRIO CI jobs, @littlejawa !

**Comment by fidencio** [comment]
Julien, welcome! <3

**Comment by littlejawa** [comment]
Thank you guys!
Happy to help where I can :-)
