### ISSUE TITLE
Adding @yaoyinnan to the kata-containers team

### ISSUE THREAD

**Issue by liubin** [kata-containers/community#290]
Yao Yinnan(@yaoyinnan), is a grade 21 graduate student from Guangzhou University. His main research interests are containers and virtualization, especially container runtime security.

After an in-depth understanding of the Kata Containers project and the open-source community, he participated in the local container open-source community organized by Ant Group in January 2022. The community's main content is organizing students to participate in security containers.

In the early days, he mainly built the Kata Containers development environment from the developer's point of view and worked on the adaptation with other projects (such as OpenYurt, a non-intrusive edge computing platform). Later, he continued to participate in the bug-fixing work of the Kata community.

From June to September 2022, he deeply participated in the development and maintenance of the Kata community through the 2022 Open Source Promotion Plan (OSPP) mission of the Institute of Software, Chinese Academy of Sciences, "Kata Containers supports cgroup v2", and have a comprehensive and profound understanding of cgroups, the task has been successfully completed.

And he will keep the focus on Kata Containers and virtualization technologies and contribute to the Kata Containers community.
Refs:

- https://github.com/kata-containers/kata-containers/pulls?q=is%3Apr+author%3Ayaoyinnan
- https://github.com/kata-containers/tests/pulls?q=is%3Apr+author%3Ayaoyinnan

Cc @kata-containers/architecture-committee @kata-containers/kata-containers-maintainer

**Comment by bergwolf** [comment]
+1, thank you for all organizing the local student community and welocme to the team @yaoyinnan !

**Comment by fidencio** [comment]
+1, and welcome!

**Comment by liubin** [comment]
Thank you all.
