### ISSUE TITLE
Add Arron Wang (@arronwy) to the project's contributors / maintainers

### ISSUE THREAD

**Issue by fidencio** [kata-containers/community#304]
Arron is one of the most reliable engineers I've worked inside Intel, and has been doing a great work on the Kata Containers / Confidential Containers integration.

Arron's worked in the TDX part, taking care of features like trusted storage, image-rs, measured boot, and he's the one who set up and is taking care of the TDX CIs that are running on every PR reaching CCv0 branch.

* https://github.com/kata-containers/kata-containers/pulls?q=is%3Apr+author%3Aarronwy
* https://github.com/kata-containers/tests/pulls?q=is%3Apr+author%3Aarronwy

**Comment by sameo** [comment]
I just wonder how come he's not a maintainer already...+100 from me.

**Comment by amshinde** [comment]
+1 from me

**Comment by mkbhanda** [comment]
+100

**Comment by bergwolf** [comment]
+1, welcome @arronwy !

**Comment by fidencio** [comment]
I've added @arronwy as part of the maintainers!

Arron, welcome, and keep rocking!

**Comment by arronwy** [comment]
Thank you all! I am so happy and honored to be part of the Kata team!
