### ISSUE TITLE
elections/tools: Committers to non-default branches don't get a vote?

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/community#310]
Based on the community [guidelines](https://github.com/kata-containers/community#contributor):
> A Contributor to the Kata Containers project is someone who has had code merged within the last 12 months. Contributors are eligible to vote in the Architecture Committee elections.

I'm not sure this is clear if you do, or don't have to commit code to the `main` branch of the repos or not?
I have a number of colleagues that have contributed code to the `CCv0` branch, but didn't receive emails to vote in the Kata Containers Architecture Committee elections, so it would be good to understand if:
1. These were accidentally missed off the email list by the tooling not considering non-default branches
2. `CCv0` commits don't count as being a committer, in which case maybe the description could be clarified?

Thanks!

**Comment by fidencio** [comment]
@stevenhorsman, thanks for bringing this one up.

I sincerely think we have missed that so far, and I've raised a PR fixing the issue.
I've checked with @sameo, and it seems that generating a diff between the previous list and the one generated with #311 applied, and then sending the voting invitation for the ones missing is something possible to do.
