### ISSUE TITLE
Add  Hyounggyu Choi @BbolroC to the project's contributors / reviewers / maintainers list

### ISSUE THREAD

**Issue by stevenhorsman** [kata-containers/community#314]
Choi has been working at the primary maintainer of the s390x pipeline for the past 8 months on 'vanilla' kata-containers and recently on the CoCo CI pipeline as well. 

* https://github.com/kata-containers/kata-containers/pulls?q=is%3Apr+author%3ABbolroC
* https://github.com/kata-containers/tests/pulls?q=is%3Apr+author%3ABbolroC

**Comment by fidencio** [comment]
Huge +1 from me!

**Comment by bergwolf** [comment]
+1, welcome Choi!

**Comment by sameo** [comment]
+1 from me as well. Welcome Choi!

**Comment by fidencio** [comment]
I've added @BbolroC to the maintainers team!  Welcome Choi!
