### ISSUE TITLE
Add @jepio as a commiter of the project

### ISSUE THREAD

**Issue by fidencio** [kata-containers/community#324]
Jeremi Piotrowski is a new contributor to the project, who has been proving to be a very welcome addition to the team.

So far Jeremi has worked mostly on Confidential Containers related subjects, but has also shown technical skills to dive into the osbuilder, and agent code, pretty much without the need for guidance.

Jeremi is also interested on helping with our Jenkins / CI instances, and will be a great asset to help us to review MSFT specific contributions when those start popping up.

With everything said in mind, I'd like to have @jepio added as a contributor (not yet a maintainer, but that will depend on how things will progress in the coming months).

https://github.com/kata-containers/kata-containers/pulls?q=is%3Apr+author%3Ajepio

**Comment by BbolroC** [comment]
+1 welcome, @jepio!

**Comment by stevenhorsman** [comment]
+1 from me. @jepio was super useful helping with the CoCo 0.4 release and other changes beyond that!

**Comment by jiangliu** [comment]
+1 welcome, @jepio!

**Comment by fidencio** [comment]
With the majority of the AC agreeing to the addition, plus a +1 from very active community members, I've added @jepio to the commiters group.

Welcome @jepio, and keep rocking!

**Comment by bergwolf** [comment]
welcome @jepio!

**Comment by jepio** [comment]
Thank you very much!
