### ISSUE TITLE
Document how the kata logo may be used

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/community#33]
I saw a comment somewhere (slack?) where someone was asking whether they could use the kata logo.

We need to document acceptable usage of it and provide an official set of versions of the logo (different background colours, svg + different png-formatted versions, etc).

/cc @annabellebertooch, @gnawux, @egernst, @grahamwhaley.`

**Comment by annabellebertooch** [comment]
Thanks for opening this! I will look into if it is okay to put them up here, or if we need to put them on the website where there is an agreement action (ie click to agree--see https://www.openstack.org/brand/openstack-logo/ as an example).

**Comment by annabellebertooch** [comment]
Legal team is reviewing the trademark requirements and sorting out how to proceed (ie if they can live on github, or if they need to live behind a "click" of agreement to the license.)

**Comment by jodh-intel** [comment]
Great! Thanks @annabellebertooch :smile:
