### ISSUE TITLE
Add @zvonkok to the maintainers team

### ISSUE THREAD

**Issue by fidencio** [kata-containers/community#346]
@zvonkok has been deeply involved in the GPU work with both Kata Containers and Confidential Containers, and I'd like to have him officially as part of the contributors team.

Zvonko is currently employed by NVIDIA, but regardless of the employer, Zvonko is a very hands-on knowledgeable engineer, with strong background in Open Source, and with a passion for doing community work.

/cc @kata-containers/architecture-committee

**Comment by stevenhorsman** [comment]
+1 from me!

**Comment by bergwolf** [comment]
+1, welcome!

**Comment by fengwang666** [comment]
+1. Welcome!

**Comment by BbolroC** [comment]
+1, welcome!

**Comment by c3d** [comment]
Indeed! Warm welcome, @zvonkok. GPUs matter.

**Comment by bergwolf** [comment]
Added @zvonkok to the maintainer team. Thanks!
