### ISSUE TITLE
contributors: Add Aurélien Bombo (@sprt) to the list of contributors

### ISSUE THREAD

**Issue by fidencio** [kata-containers/community#347]
Aurélien is employed by Microsoft and has been immensely helping us with the migration from Jenkins to GitHub Actions.

I'd like to hear from the other members of the A/C about the possibility to add him as part of our contributors, allowing him to run tests by his own (which is quite essential for what we've been doing), and also having his reviews officially counted.

https://github.com/kata-containers/kata-containers/pulls/sprt for reference.

**Comment by fengwang666** [comment]
+1

**Comment by BbolroC** [comment]
+1 Welcome, @sprt !

**Comment by bergwolf** [comment]
+1

**Comment by jiangliu** [comment]
+1

**Comment by fidencio** [comment]
I've added Aurélin to the committers team. <3

**Comment by sprt** [comment]
Thank you all, I'm very pleased to be joining the team! 🙂
