### ISSUE TITLE
Add Wedson Almeida Filho (@wedsonaf) as part of the committers / maintainers

### ISSUE THREAD

**Issue by fidencio** [kata-containers/community#348]
@wedsonaf is employed by Microsoft and has been contributing to the project for a while, mainly focusing on the "Confidential Containers" integration.

Wedson has been doing some very nice cleanups, and has also participated on the push for big and important feataures related to "Confidential Containers", such as the tardev-snapshotter, image pulling (on the host), and the policy work (presented and worked together with @danmihai1).

My ask for the @kata-containers/architecture-committee is to get an official approval to have @wedsonaf added to the contributors / maintainers list.

References:
* https://github.com/kata-containers/kata-containers/pulls/wedsonaf
* https://github.com/kata-containers/tardev-snapshotter

**Comment by bergwolf** [comment]
+1, welcome @wedsonaf !

**Comment by BbolroC** [comment]
+1 welcome @wedsonaf !

**Comment by fidencio** [comment]
@wedsonaf, welcome aboard!
