### ISSUE TITLE
Moving Architecture Committee vote to September

### ISSUE THREAD

**Issue by annabellebertooch** [kata-containers/community#35]
In our current governance policies, we are due to vote on three Architecture Committee seats (@jessfraz @tallclair and @WeiZhang555) in June. However this was written when we were anticipating a Q1 launch.  I'd like to propose we push the vote to early September, and consequently push the vote for @sameo and @gnawux's seats to February. We would then stay on the Sept/Feb voting cycle. 

Looking to the Architecture Committee to vote on this issue, but open to suggestions and discussion from all.

**Comment by grahamwhaley** [comment]
+1 from me. I have no issues with us pushing the vote out, this time ;-)

**Comment by raravena80** [comment]
👍

**Comment by jessfraz** [comment]
SGTM

**Comment by sameo** [comment]
LGTM

**Comment by WeiZhang555** [comment]
LGTM

**Comment by gnawux** [comment]
+1

**Comment by tallclair** [comment]
LGTM
