### ISSUE TITLE
Add Dan Mihai (@danmihai1) as a maintainer / contributor to the project

### ISSUE THREAD

**Issue by fidencio** [kata-containers/community#355]
Dan is an engineer working for MSFT and has been deeply involved in making Kata Containers ready for CoCo usage, specifically on the "Policies and Secure configuration" front.

Dan has presented this topic as part of the AC (see: https://us06web.zoom.us/rec/share/ewG0h_RJC6Hnfy2X9CSiCMbb1oGxPPKGHmWPEi_v-_f45COd4GUk8XS8TcEwlzAa.GSGDHWHygkt8qJkY) and has promptly followed up with the implementation covering runtime / agent / tests, and he's for sure the most relevant person to officially become a maintainer for that area.

https://github.com/kata-containers/kata-containers/pulls/danmihai1

**Comment by bergwolf** [comment]
+1, wecome @danmihai1

**Comment by BbolroC** [comment]
+1, welcome @danmihai1 !

**Comment by stevenhorsman** [comment]
Sounds good to me, thanks @danmihai1 for the contributions past and future!

**Comment by egernst** [comment]
sgtm

**Comment by fidencio** [comment]
@danmihai1, welcome! <3

**Comment by danmihai1** [comment]
Thanks @fidencio , @bergwolf , @BbolroC @stevenhorsman @egernst and everyone else from the community!
