### ISSUE TITLE
Remove maintainers who are not active anymore

### ISSUE THREAD

**Issue by fidencio** [kata-containers/community#356]
Carlos, Feng, and Julio are still maintainers of the project, although not activelly working on the project anymore.

We're super thankful for all the hardwork, bugs, features, improvements they provided to the project, but doesn't make sense to keep them as maintainers.

**Comment by bergwolf** [comment]
Are they part of the contributors or committers group? We'd like to still have them in the community, even not as maintainers.

**Comment by fidencio** [comment]
> Are they part of the contributors or committers group? We'd like to still have them in the community, even not as maintainers.

Carlos is part of the `kata-containers-committer` group. Feng and Julio are not, but they should be added.

**Comment by fidencio** [comment]
I've added both Julio and Feng to the committers group, now the three of them are there.

**Comment by egernst** [comment]
I miss all of these guys! keeping in commuter group, but removing fro maintainers sgtm.

**Comment by fidencio** [comment]
Done!
