### ISSUE TITLE
Add stratovirt maintainers to the team

### ISSUE THREAD

**Issue by fidencio** [kata-containers/community#377]
Folks, with stratovirt work merged for the go runtime and the coming work for the rust runtime, we need to add @fadecoder and @WenyuanLau to the maintainers list.

Once I get the approval from the other AC members, I'll go ahead and do this.

**Comment by WenyuanLau** [comment]
Thanks @fidencio

**Comment by BbolroC** [comment]
+1, welcome @WenyuanLau !

**Comment by fidencio** [comment]
As @WenyuanLau has been added, I'm closing this one.
