### ISSUE TITLE
Add Ryan Savino as part of the committers team

### ISSUE THREAD

**Issue by fidencio** [kata-containers/community#379]
Folks, @ryansavino is an AMD contributor who's been involved with the Confidential Containers usage of Kata Containers, and is the main maintainer ofc the AMD CI.

Here you can see all the contributions coming from Ryan:
* kata-containers: https://github.com/kata-containers/kata-containers/pulls/ryansavino
* tests: https://github.com/kata-containers/tests/pulls/ryansavino

As setting up the CI machine, and making sure it works requires the committer access, the least we can do is adding the folks who have a proven history of contributing to the project to be gain such access.

**Comment by stevenhorsman** [comment]
+1 here. Thanks for the contributions so far Ryan!

**Comment by jepio** [comment]
+1

**Comment by gkurz** [comment]
+1

**Comment by wainersm** [comment]
+1. Thanks Ryan! And remember: with great powers...
... comes great opportunities to mess with CI! :D

**Comment by sameo** [comment]
+1. Welcome @ryansavino!

**Comment by danmihai1** [comment]
+1, welcome to the team @ryansavino!

**Comment by lifupan** [comment]
+1,  Glad to join the kata team @ryansavino

**Comment by BbolroC** [comment]
+1, welcome to the team @ryansavino! 😉

**Comment by fidencio** [comment]
I've added @ryansavino to the commiters team, thanks!
