### ISSUE TITLE
GitHub access for non-org members?

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/community#38]
We should probably discuss and define a policy for how we let community members (who are not, at least at present, members of the [github kata-containers org](https://github.com/orgs/kata-containers/people) access the project. Currently they are limited I believe to some moderately restrictive read-only mode, which carries a couple of potential downsides:
- they cannot assign themselves issues
- they cannot see who the kata members are, or what teams they are in

Now, that may or may not be an issue - we should discuss.

Also, maybe we'd like to discuss and define how somebody can or does become or request to become a member of the kata-containers org. afaik, the members were fixed when the org was formed, and I don't believe we have a method to request, review or add new members.

I do wonder if the [github outside collaborators](https://help.github.com/articles/adding-outside-collaborators-to-repositories-in-your-organization/) feature could be useful in some form?

/me notes that @annabellebertooch is not a member of the kata org afaict btw ;-)

**Comment by jodh-intel** [comment]
I've now added @annabellebertooch to the org.

**Comment by grahamwhaley** [comment]
Oooh ooh, but but ... we don't have a process for that ;-)

**Comment by jodh-intel** [comment]
I'll say we're blocked on waiting for someone to write a process for creating a new process :)

**Comment by jodh-intel** [comment]
Assigned to @annabellebertooch as discussed on Slack.
