### ISSUE TITLE
Add Beraldo Leal as part of committers team

### ISSUE THREAD

**Issue by wainersm** [kata-containers/community#380]
@beraldoleal is a software engineer at Red Hat who has engaged with Kata Containers to mainly:
 * help on the CoCo's "merge to main" initiative
 * enable CoCo's cloud-api-adaptor to use kata's runtime from main so to unblock adding support for GCP. 

Recently he switched the whole project out of GoGoProtobuf, a work that required a considerable amount of changes but that was delayed due to his inability to run CI jobs. Thus, my request to add him on committers team aims to allow him to trigger CI on the PRs he will be reviewing as well as contributing.

Beraldo's code contributions:
 * https://github.com/kata-containers/kata-containers/pulls?q=author%3Aberaldoleal
 * https://github.com/kata-containers/tests/pulls?q=author%3Aberaldoleal

**Comment by wainersm** [comment]
FYI @kata-containers/architecture-committee

**Comment by stevenhorsman** [comment]
+1 from me. Welcome Beraldo!

**Comment by gkurz** [comment]
+1, bem-vindo Beraldo ! :-)

**Comment by fidencio** [comment]
A huge +1 from my side! :-)

**Comment by danmihai1** [comment]
+1. Welcome to the team, Beraldo!

**Comment by lifupan** [comment]
+1 Welcome Beraldo ! :-)

**Comment by fidencio** [comment]
Beraldo's been added, welcome! <3

**Comment by beraldoleal** [comment]
Thank you all.
