### ISSUE TITLE
Add @ChengyuZhu6 as part of the maintainers group

### ISSUE THREAD

**Issue by fidencio** [kata-containers/community#383]
@ChengyuZhu6 has been doing an amazing work on the Kata Containers and Confidential Containers front and this expands the Kata Containers community.

He's been deeply involved in the image-pull effort, and has working on different projects to be able to close the gaps on our side, and proivide a better product to the Confidential Containers project.

Here you can find @ChengyuZhu6's contributions to the Kata Containers:
https://github.com/kata-containers/kata-containers/pulls?q=author%3AChengyuZhu6
https://github.com/kata-containers/tests/pulls?q=author%3AChengyuZhu6

**Comment by stevenhorsman** [comment]
Complete agreement from me. Thanks Chengyu for all the amazing work!

**Comment by BbolroC** [comment]
Absolutely! +1 from me. Thanks a lot @ChengyuZhu6!

**Comment by jepio** [comment]
+1, thanks for your work

**Comment by jiangliu** [comment]
+1, thanks for your great work:)

**Comment by danmihai1** [comment]
Sounds good - welcome Chengyu!

**Comment by GabyCT** [comment]
+1 :)

**Comment by arronwy** [comment]
+1, welcome :)

**Comment by gkurz** [comment]
+1

**Comment by bergwolf** [comment]
+1, welcome!

**Comment by fidencio** [comment]
@ChengyuZhu6, you've been added as part of the maintainers.
Keep rocking!

**Comment by ChengyuZhu6** [comment]
Thank you for the recognition and the opportunity to work on kata and coco. I enjoyed collaborating with you all and learning from you!
