### ISSUE TITLE
Add @Redent0r to the project's contributors

### ISSUE THREAD

**Issue by fidencio** [kata-containers/community#403]
Saul Paredes (@Redent0r), from MSFT, has been working with us constantly since the beginning of the year, and has been one of the main folks behind genpolicy.

You can get familiar with Saul Paredes work here: https://github.com/kata-containers/kata-containers/pulls?q=is%3Apr+is%3Aopen+Redent0r

I'd like to ask the current @kata-containers/architecture-committee members for their opinions and feedback on this!

**Comment by BbolroC** [comment]
+1 from me, welcome @Redent0r!

**Comment by stevenhorsman** [comment]
+1 Thanks for the contributions so far and welcome

**Comment by lifupan** [comment]
+1 from me, welcome @Redent0r, too!

**Comment by gkurz** [comment]
> Saul Paredes (@Redent0r), from MSFT, has been working with us constantly since the beginning of the year, and has been one of the main folks behind genpolicy.
> 
> You can get familiar with Saul Paredes work here: https://github.com/kata-containers/kata-containers/pulls?q=is%3Apr+is%3Aopen+Redent0r
> 

This log definitely originates from a dedicated and steady contributor.

> I'd like to ask the current @kata-containers/architecture-committee members for their opinions and feedback on this!

+1

Welcome Saul !

**Comment by fidencio** [comment]
I've added Saul as part of the contributors, thank y'all.
