### ISSUE TITLE
Process: How to become a github PR approver

### ISSUE THREAD

**Issue by raravena80** [kata-containers/community#60]
Related to https://github.com/kata-containers/community/issues/59

We need a process on how to become a pull approve approver for each of the repos individually.

@kata-containers/architecture-committee @annabellebertooch @WeiZhang555 @jodh-intel @egernst @grahamwhaley

**Comment by WeiZhang555** [comment]
I agree. We can discuss more details and make a formal document for user reference :smile:

**Comment by gnawux** [comment]
We defined it here: https://github.com/kata-containers/community#maintainer in general, but we should have more detail processes indeed.

**Comment by grahamwhaley** [comment]
Ah, thank you @gnawux - I think it is so long since we added anybody, we have all forgotten ;-)
But, yes, we should firm that up and make it more obvious how on applies and qualifies.

**Comment by raravena80** [comment]
@jodh-intel  sounds good! Also, another aspect would be to make it challenging but not extremely difficult that would discourage people to become approvers/maintainers. I added https://github.com/kata-containers/community/issues/60 and https://github.com/kata-containers/community/issues/59 to the next meeting agenda.

**Comment by annabellebertooch** [comment]
Per @marcov's post on the kata-dev ML...in the last Arch Committee meeting about this, it was left as, "1) We will update a maintainers file for easier access to the people and then 2) To become an approver, contact this list." 

@grahamwhaley IIRC, you had a crafty way to avoid duplication of lists in the works?
