### ISSUE TITLE
Docs: Who manages which resources that Kata uses

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/community#71]
**(this is WIP - I'll start adding details - but if you know of anything missing or have details to add either (if you can) add them yourselves, or leave a comment and I will fold them in. If you are mentioned below, please check you are in the right slot etc. :-)
Eventually this will become a markdown doc or wiki page - probably the former)**

Kata uses a number of resources, particularly to drive its CI system for instance. Most of those resources require some sort of access control (keys, logins, rights etc.) to configure, deploy or manage. We don't have a definitive list of what those resources are, or who can access them to maintain them. This can be a fairly critical component to the project, given many of those resource are key blocking parts of the CI system.

Let's collect up a list of all the resources we know of and who currently has the ability to manage them - then we can decide if we need to have a central place to lodge 'credentials', and also if we need to diversify access to avoid any [bus factor](https://en.wikipedia.org/wiki/Bus_factor) effects.

| What | Primary | Others | Notes |
| ---- | ------- | ------- | ------ |
| [Jenkins Master](http://jenkins.katacontainers.io) | @chavafg | @GabyCT @grahamwhaley | VM hosted on Vexxhost |
| Jenkins vexxhost slaves | @chavafg  | @GabyCT | |
| Jenkins Azure slaves | @chavafg | @egernst  | |
| Zuul CI configuration | @grahamwhaley @ttx | [OpenDev infra core](https://review.openstack.org/#/admin/groups/306,members) | |
| Packet.net metrics CI slaves | @grahamwhaley  | | https://github.com/kata-containers/ci/issues/6 |
| IBM Power8 CI slaves | @nitkon | @grahamwhaley | https://github.com/kata-containers/tests/issues/1043 |
| IBM S390 CI slaves | @alicefr, @jschintag, @tuan-hoang1 | @chavafg | **Add other IBM folks to the list **  https://github.com/kata-containers/kata-containers/issues/33 |
| Github management | @kata-containers/architecture-committee @chavafg @grahamwhaley @jodh-intel  | | Quite a few members of the Kata org have github 'power' if necessary |
| [Travis CI](https://travis-ci.org/kata-containers) | @jodh-intel | | https://github.com/kata-containers/kata-containers/issues/22 |
| [Pullapprove](https://pullapprove.com/kata-containers) | @sameo @jodh-intel | | |
| [CodeCov](https://codecov.io/gh/kata-containers) | @sboeuf @jodh-intel | | |
| Zoom meetings | @ClaireMassey | | |
| Slack channels | @sameo ?? *add Claire here* | | |
| freenode IRC channels | @jbryce + [OpenDev IRC ops](https://git.openstack.org/cgit/openstack-infra/project-config/tree/accessbot/channels.yaml#n83) | | |
| Etherpad docs | [OpenDev infra core](https://review.openstack.org/#/admin/groups/306,members) |  | |
| [Website](https://katacontainers.io) | ??? * add Claire here? * | | |
| [Twitter handle](https://twitter.com/katacontainers) ? | * Claire ? * | | |
| [Facebook page](https://www.facebook.com/KataContainers) ? | * Claire ? * | | |
| [OBS](https://build.opensuse.org/project/show/home:katacontainers) | @marcov | @jcvenegas | http://download.opensuse.org/repositories/home:/katacontainers:/ |
| github [katabot](https://github.com/katacontainersbot) | @chavafg | @grahamwhaley  | |
| Kata docker hub | @egernst | @mcastelino @chavafg  | https://hub.docker.com/u/katadocker |
| Community [activity dashboard](https://katacontainers.biterg.io) | @ttx @ClaireMassey | | Run by Bitergia |
| packagecloud | @jcvenegas @marcov | @ttx | |

**Comment by jodh-intel** [comment]
Added links to some of the resources and an issue.

**Comment by jodh-intel** [comment]
Added OBS + Facebook.

**Comment by jodh-intel** [comment]
@grahamwhaley - what about that metrics site you were using? Also anyone know what the status of waffle.io is?

**Comment by jodh-intel** [comment]
It could be useful to add a couple of extra columns:

- Alternative provider?
- ICE: if the provider suffers an outage, how do we temporarily recover (if possible)?
  For example, if pullapprove died, we'd disable the github hook and just do manual reviews.
- Critical (could we survive without it)?

**Comment by jodh-intel** [comment]
True. But I guess it depends what our plans are here. Is this a one-off exercise, or do we plan to keep the information current? I'd hope we opt for the latter and if so it would be good to get a feel for the bus-factor / disaster recovery exposure of all the externals we consume.

Which reminds me, we should add our versions database which of course specifies all external software dependencies we use:

- https://github.com/kata-containers/runtime/blob/master/versions.yaml

All the URL refer to github.com (surprise! ;) but we also have a ref to https://www.kernel.org/ in there which should prolly be recorded.

**Comment by grahamwhaley** [comment]
My plan was to record where all the 'secrets' and people and needs for 'special access' were, so we could ensure we have multiple people having access to each item (so we don't lose a critical key or password etc.).
The versions.yaml file is just a file in our repos - anybody can PR a change to it?

**Comment by jodh-intel** [comment]
Ah - your scary bold text distracted me from the essence of the table ;)

Well, ok, we could just do that. Or we could collate "everything". I totally agree we need to know who holds keys, etc. But bus factor also affects the services themselves surely?

One other point: regardless of scope - it might be useful to identify which region each "manager" is in since ideally we'd have full regional cover.

**Comment by grahamwhaley** [comment]
Added the kata bot github user. Also, I think the table may not be triggering github 'you have been referenced' nudges, so extracting the current list of usernames implicated here as a massive CC :-)

Please check the table at the top of this PR and edit or let us know if you need add/removing from it!

---
@alicefr
@cboylan
@chavafg
@egernst 
@fungi 
@GabyCT 
@grahamwhaley 
@jcvenegas
@jodh-intel 
@kata-containers/architecture-committee
@marcov
@nitkon
@sameo
@sboeuf
@ttx 
@ClaireMassey

**Comment by jodh-intel** [comment]
Thanks @alicefr - table updated.

**Comment by mcastelino** [comment]
@grahamwhaley  Eric, Salvador and myself have rights on the kata dockerhub.

**Comment by grahamwhaley** [comment]
Hmm, this page/Issue has been fairly static now for a while, and is probably useful.... I'll try to get around to making it an official doc on this repo, but I suspect that won't happen in the next 1.5weeks....

**Comment by grahamwhaley** [comment]
@egernst @gnawux - err, what do you think, about time I turned this into either a PR or a wiki page - maybe a wiki page is the right direction here??
