### ISSUE TITLE
VMT: create VMT (closed) mailing list

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/community#78]
I'd like to see if we can have a mailing list for the VMT members.
The list should be 'closed' (that is, not public), and would be used for:

- an endpoint for reports to the VMT to come in
- a place to subscribe, for instance to the [open containers security announcement list](https://github.com/opencontainers/org/blob/master/security.md#disclosure-distribution-list)

@fungi - is this something we can set up. If so, then I'll update the docs and subscribe the list to the above.

/cc @ttx @vbatts

**Comment by fungi** [comment]
> I'd like to see if we can have a mailing list for the VMT members.

The OSF staff don't operate any mailing list servers (you'd need one requested from the Infra/OpenDev community and raising an issue in a proprietary defect tracker is not an efficient way to reach them), so I'm going to assume you're actually asking for advice on whether or not this is a sound idea.

> The list should be 'closed' (that is, not public), and would be used for:
> 
>     * an endpoint for reports to the VMT to come in

Open communities are built on personal trust and reputation. It's far better to list individual contacts and their encryption keys, and recommend those who want to report suspected vulnerabilities by E-mail reach out to those people directly with their concerns. When those same individuals engage in discourse on public mailing lists or send announcements and sign with their keys, this helps build the positive reputation on which ecosystem/downstream/user trust is ultimately based. Your VMT members are the faces of information security in your project, and hiding them behind a generic mailing list address or alias does them and your community a disservice.

For examples, see https://security.openstack.org/#how-to-report-security-issues-to-openstack and https://zuul-ci.org/docs/zuul/user/vulnerabilities.html#report-via-encrypted-e-mail where the addresses and key details are provided in easy-to-find locations for those projects.
 
>     * a place to subscribe, for instance to the [open containers security announcement list](https://github.com/opencontainers/org/blob/master/security.md#disclosure-distribution-list)
[...]

Subscribing mailing lists to other mailing lists is generally considered bad form. Beyond mere etiquette concerns, it's genuinely dangerous (often leading to autoresponder loops and the like). A number of similar lists, such as https://oss-security.openwall.org/wiki/mailing-lists/distros (from where the OCSA ML seems to have copied the majority of their membership policy) explicitly require subscribers be individual representatives of their projects and does not allow aliases to be subscribed at all. This is for good reason.
