### ISSUE TITLE
Should Kata get a NIST/NVD CPE allocation?

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/community#87]
CVE databases etc. use 'Common Platform Enumeration' to detail which products and versions are susceptible to which vulnerabilities.

Now we are starting to process KCSA and KCSN's in the VMT, Should Kata apply for a CPE identifier?
I don't know if the OSF have any precedence or background in this, and maybe already have some appropriate designations? I'd go grab some refs, but the nist website seems to be down!

I was thinking we'd maybe have a CPE of 'osf:kata' or 'kata:kata' for instance.

/cc @ttx @ClaireMassey @fungi @kata-containers/architecture-committee

**Comment by fungi** [comment]
The OpenStack project hasn't applied for any CPE identifiers, our VMT just puts consistent project names and affected version ranges into the appropriate fields of the CVE request form. Looking at the current (2.3) CPE Dictionary, it appears someone (presumably MITRE?) has created cpe-item entries for many of OpenStack's subprojects' releases but we've never explicitly leveraged those in our vulnerability reporting. A random example is cpe-item `cpe:/a:openstack:compute:12.0.0` with title `Openstack Compute (Liberty) 12.0.0`.

If you're interested in going through the process of applying for CPE identifiers yourself I'm interested to hear how it goes, but in my experience it's not been an especially necessary part of vulnerability management.

**Comment by grahamwhaley** [comment]
Thanks @fungi  I suggest we wait a short while after we submit our first Kata related CVE and see if a relevant CPE appears. If by the time we get to our second CVE report and there is still no CPE, then maybe we chase it up.
